### ISSUE TITLE
FoLiA-stats gives wrong counts for tokens and percentages with --max-ngram

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/foliautils#13]
FoLiA-stats: with parameter --max-ngram='3', the token counts for 2- and 3-grams and most certainly the percentages calculated for all ngrams are incorrect.
In comparison to the results with --ngram='1', token counts for unigrams appear to be correct.

Example command line: reynaert@black:~$ for year in 1932 ; do nohup /exp/sloot/usr/local/bin/FoLiA-stats -p --max-ngram='3' --class='OCR' -s --hemp=hempfile -t 60 -e gz$ -o /reddata/NLAB/KBkranten/FOLIAlangcat/FRQ/FOLIAstats.KBkranten$year /reddata/NLAB/KBkranten/FOLIAlangcat/$year/artikel >/reddata/NLAB/KBkranten/FOLIAlangcat/FRQ/FOLIAstats.KBkranten$year.20171106.RED.stdout 2>/reddata/NLAB/KBkranten/FOLIAlangcat/FRQ/FOLIAstats.KBkranten$year.RED.20171106.stderr ; done &

Example output:

reynaert@black:~$ tail -n 3 /reddata/NLAB/KBkranten/FOLIAlangcat/FRQ/FOLIAstats.KBkranten1900.*.tsv
==> /reddata/NLAB/KBkranten/FOLIAlangcat/FRQ/FOLIAstats.KBkranten1900.wordfreqlist.2-gram.tsv <==
✓■TT »g"«,"l«l«in«r.	1	76013696	33.3219
❖ *	1	76013697	33.3219
❖ Het	1	76013698	33.3219

==> /reddata/NLAB/KBkranten/FOLIAlangcat/FRQ/FOLIAstats.KBkranten1900.wordfreqlist.3-gram.tsv <==
✓■TT »g"«,"l«l«in«r. Re	1	75189431	32.9606
❖ * *	1	75189432	32.9606
❖ Het voorgenomen	1	75189433	32.9606

==> /reddata/NLAB/KBkranten/FOLIAlangcat/FRQ/FOLIAstats.KBkranten1900.wordfreqlist.tsv <==
✓•	1	76915900	33.7174
✓•15°.	1	76915901	33.7174
✓■TT	1	76915902	33.7174
reynaert@black:~$

Sample test files are to be found here (also accessible from Red):
reynaert@black:~$ ls -l /reddata/NLAB/KBkranten/FOLIAlangcat/TEST                              
total 332
-rw-r--r-- 1 reynaert reynaert 294944 Apr 25  2017 ddd.010126865.mpeg21.a0001.lang.folia.xml
-rw-r--r-- 1 reynaert reynaert   8354 Apr 25  2017 ddd.010126865.mpeg21.a0002.lang.folia.xml
-rw-r--r-- 1 reynaert reynaert  21523 Apr 25  2017 ddd.010128079.mpeg21.a0001.lang.folia.xml.gz
-rw-r--r-- 1 reynaert reynaert    788 Apr 25  2017 ddd.010128079.mpeg21.a0002.lang.folia.xml.gz

**Comment by kosloot** [comment]
You make it very difficult to reproduce/debug this:
- you command runs on 1932 it seems
- the apparently wrong output is from 1900
- unclear is WHAT is wrong or WHY you think it is wrong. The tail will have counts of 1. 
- I really can't debug on  such a big dataset. Please extract a toy example with a dozen short files or so and then show me which counts are wrong.

**Comment by martinreynaert** [comment]
My command has run on 40, highly similar, years of this. All the output is in the same directory given in the command line. You have access to that.

Sure the tail has outputs of 1, i.e. hapaxes. The program would be all the more buggy if it did not.

This being the tail, the percentages should tally to 100% They tally to about 1 third of that. This suggests to me that for all three lists produced you take the sum total of all the tokens/ngrams of all three lists to calculate the percentage, instead of the total number of tokens per list.

The total token counts for 2- and 3-grams are suspect. They are lower than the unigram count.

Unigram counts, as stated, were verified by running with --ngran='1'.

I have given you the link to a small test set of files. The first file in the list has just one paragraph with an easily verifiable number of tokens. However, when run of small batches of files like this, results were even harder to interpret.

**Comment by kosloot** [comment]
sorry about mis interpreting the output of LS, thought it stated 332 file were there :{
- The percentage is fishy indeed. should reach 100% at some time. Your guess might be right
- having less 2 or 3 grams the unigrams is quite good to understand, I think
a sentence like "dit is een test" has 4 unigrams, 3 2-grams and 2 3-grams.
This is triggered by the -s option, (--tags=p would be preferred) which takes text in paragraphs
If you want to take the whole document as 1 big blob of text, you need --tags=text, although I am not sure if that would work. (if not, THAT is a bug for sure..)

**Comment by kosloot** [comment]
the percentage is fixed now. per language AND per n-gram
Still unclear what might be wrong with the 2 and 2-gram counts

**Comment by kosloot** [comment]
Is thus issue solved now? If not: please give more details.

**Comment by kosloot** [comment]
assume it is fixed
