### ISSUE TITLE
FoLiA-collect: -t parameter does not work

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/foliautils#14]
FoLiA-collect appears to use only 1 thread, even when the -t switch is set to a higher number.

Some user feedback: Even so, it did manage to successfully collect the 40 unigram lists derived from the years 1900-1939 of the KB newspapers. With the bigram lists on server Red (256GB of RAM) it went into swap. So I killed it, noticing afterwards only that it had successfully written out 75% of the collected list.

**Comment by kosloot** [comment]
One remark about the size issue. Fixing -t only will assure that the memory limit is reached sooner. :)

**Comment by kosloot** [comment]
A fix is in GIT now

**Comment by kosloot** [comment]
assume this is OK now
