### ISSUE TITLE
FoLiA-collect Summary of frequency file statistics in stdout

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/foliautils#15]
It would be nice if FoLiA-collect would also report the same kind of frequency file information as FoLiA-stats, i.e. number of tokens and types and the type-token ratio.

**Comment by kosloot** [comment]
A first attempt is in GIT now.

**Comment by kosloot** [comment]
@martinreynaert can I close this one? PLEASE test

**Comment by kosloot** [comment]
closing this, assuming it works
