### ISSUE TITLE
FoLiA-stats problem with n-grams?

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/foliautils#19]
@martinreynaert meldt:
ik ben zelf onlangs gestoten op wat een backward compatibility probleem lijkt met FoLiA-stats: het leek mij onmogelijk nu om 2- en 3-gramlijsten te krijgen uit de SoNaR FoLiA-bestanden die in distributie zijn. Is dat mogelijk? Het lijkt mij althans een probleem.

**Comment by kosloot** [comment]
@martinreynaert : geef SVP een of 2 voorbeeldfiles waar het mis gaat.

**Comment by martinreynaert** [comment]
Er staan 10 testfiles uit de 'periodicals' van SoNaR500 op /reddata:

reynaert@black:/reddata/sloot/FOLIA/SONAR500$ ls -l
total 4704
-rw-r-xr-- 1 reynaert reynaert  273836 Mar  7 11:25 WR-P-P-H-0000002500.folia.xml
-rw-r-xr-- 1 reynaert reynaert  710105 Mar  7 11:25 WR-P-P-H-0000002501.folia.xml
-rw-r-xr-- 1 reynaert reynaert  235107 Mar  7 11:25 WR-P-P-H-0000002502.folia.xml
-rw-r-xr-- 1 reynaert reynaert 1505574 Mar  7 11:25 WR-P-P-H-0000002503.folia.xml
-rw-r-xr-- 1 reynaert reynaert   87491 Mar  7 11:25 WR-P-P-H-0000002504.folia.xml
-rw-r-xr-- 1 reynaert reynaert  205809 Mar  7 11:25 WR-P-P-H-0000002505.folia.xml
-rw-r-xr-- 1 reynaert reynaert 1026090 Mar  7 11:25 WR-P-P-H-0000002506.folia.xml
-rw-r-xr-- 1 reynaert reynaert  247716 Mar  7 11:25 WR-P-P-H-0000002507.folia.xml
-rw-r-xr-- 1 reynaert reynaert  179406 Mar  7 11:25 WR-P-P-H-0000002508.folia.xml
-rw-r-xr-- 1 reynaert reynaert  327249 Mar  7 11:25 WR-P-P-H-0000002509.folia.xml

Ik probeer die zelf ook opnieuw.

**Comment by martinreynaert** [comment]
Zelfs met --ngram=1 krijg ik op <s of <p geen frequentiefile:

reynaert@black:/reddata/sloot/FOLIA/SONAR500$ /exp/sloot/usr/local/bin/FoLiA-stats --ngram=1 --tags=s -t 30 -e folia.xml -o TESTmre1 /reddata/sloot/FOLIA/SONAR500
start processing of 10 files 
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002504.folia.xml' has 8 s nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002504.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 9 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002508.folia.xml' has 12 s nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002508.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 8 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002505.folia.xml' has 11 s nodes 
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002507.folia.xml' has 12 s nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002505.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 7 files to go.
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002507.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 6 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002500.folia.xml' has 17 s nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002500.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 5 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002502.folia.xml' has 13 s nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002502.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 4 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002509.folia.xml' has 18 s nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002509.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 3 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002501.folia.xml' has 44 s nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002501.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 2 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002506.folia.xml' has 58 s nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002506.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 1 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002503.folia.xml' has 94 s nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002503.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 0 files to go.
done processsing directory '/reddata/sloot/FOLIA/SONAR500'
start calculating the results
in total 0 n-grams were found.in 10 FoLiA documents.
reynaert@black:/reddata/sloot/FOLIA/SONAR500$ /exp/sloot/usr/local/bin/FoLiA-stats --ngram=1 -s -t 30 -e folia.xml -o TESTmre1 /reddata/sloot/FOLIA/SONAR500
start processing of 10 files 
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002504.folia.xml' has 4 p nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002504.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 9 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002508.folia.xml' has 5 p nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002508.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 8 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002505.folia.xml' has 4 p nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002505.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 7 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002502.folia.xml' has 4 p nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002502.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 6 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002507.folia.xml' has 4 p nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002507.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 5 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002500.folia.xml' has 6 p nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002500.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 4 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002509.folia.xml' has 8 p nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002509.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 3 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002501.folia.xml' has 14 p nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002501.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 2 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002506.folia.xml' has 21 p nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002506.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 1 files to go.
document '/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002503.folia.xml' has 23 p nodes 
Processed :/reddata/sloot/FOLIA/SONAR500/WR-P-P-H-0000002503.folia.xml with 0 n-grams, 0 lemmas, and 0 POS tags. still 0 files to go.
done processsing directory '/reddata/sloot/FOLIA/SONAR500'
start calculating the results
in total 0 n-grams were found.in 10 FoLiA documents.
reynaert@black:/reddata/sloot/FOLIA/SONAR500$

**Comment by kosloot** [comment]
Ok, 2 problemen hier:
1. In de FoLiA staat GEEN text onder de 'p' of 's' nodes. Alleen onder 'w'.
ergo: er worden alleen 1-grammen gevonden.
2. omdat de tekst alleen onder 'w' nodes staat moet je zoeken met --tags=w 

``
/exp/sloot/usr/local/bin/FoLiA-stats --max-ngram=3 --tags=w -o /tmp/KO WR-P-P-H-0000002500.folia.xml 
start processing of 1 files 
document 'WR-P-P-H-0000002500.folia.xml' has 281 w nodes 
Processed :WR-P-P-H-0000002500.folia.xml with 281 n-grams, 0 lemmas, and 0 POS tags. still 0 files to go.
done processsing directory 'WR-P-P-H-0000002500.folia.xml'
start calculating the results
in total 281 n-grams were found.
created WordFreq list '/tmp/KO.wordfreqlist.tsv' for 1-grams. Stored 281 tokens and 153 types, TTR= 0.544484, the angle is 28.5676 degrees
created WordFreq list '/tmp/KO.wordfreqlist.2-gram.tsv' for 2-grams. Stored 0 tokens and 0 types, TTR= -nan, the angle is -nan degrees
created WordFreq list '/tmp/KO.wordfreqlist.3-gram.tsv' for 3-grams. Stored 0 tokens and 0 types, TTR= -nan, the angle is -nan degrees
``

**Comment by kosloot** [comment]
2 opmerkingen nog:
1. de output voor niet bestaande n-grams kan weggelaten worden
2. FoLiA-stats ZOU de tekst voor s en/of p kunnen opbouwen uit de woorden. Misschien een goed idee om dat toe te voegen?

**Comment by martinreynaert** [comment]
Ik begrijp 1. niet.

Wat betreft 2. Dat is wat er vroeger gedaan werd en wat ik graag opnieuw zou kunnen doen.

**Comment by kosloot** [comment]
> created  WordFreq list '/tmp/KO.wordfreqlist.2-gram.tsv' for 2-grams. Stored 0 tokens and 0 types, TTR= -nan, the angle is -nan degrees 

> created WordFreq list '/tmp/KO.wordfreqlist.3-gram.tsv' for 3-grams. Stored 0 tokens and 0 types, TTR= -nan, the angle is -nan degrees `` 

Lijkt me overbodig/verwarrend.

2. Ja, en dat kan nog steeds met de opties: ``--mode=lemma_pos --max-ngram=5``
Alleeen bleek er nog een bug in te zitten. Op red is die al gefixt, en lijkt het allemaal te werken

**Comment by martinreynaert** [comment]
Wat betreft 1. Zoals het er staat is het verwarrend. Ik wil echter wel de boodschap krijgen dat er geen ngrams gevonden werden, indien dat zo is. Dat verduidelijkt dat je de verkeerde --tag gebruikt hebt, bijvoorbeeld.

**Comment by kosloot** [comment]
de melding is aangepast
