### ISSUE TITLE
FoLiA-hocr cannot handle tif filenames starting with a number

### ISSUE THREAD

**Issue by peterdekker** [LanguageMachines/foliautils#21]
I am using FoLiA-hocr inside the Lamachine distribution. I start FoLiA-hocr with a hocr input file, which, inside the file, contains a reference to an original .tif file starting with a number.

The top of the hocr file looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>
</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name='ocr-system' content='tesseract 3.04.00' />
  <meta name='ocr-capabilities' content='ocr_page ocr_carea ocr_par ocr_line ocrx_word'/>
</head>
<body>
  <div class='ocr_page' id='page_1' title='image "00529957.tif"; bbox 0 0 1890 2598; ppageno 0'>
```

This gives the following output:

$ FoLiA-hocr -O /tmp 00529957.hocr
terminate called after throwing an instance of 'folia::XmlError'
  what():  XML error: '00529957.tif' is not a valid NCName.
Afgebroken

When using tif files starting with a letter, there is no problem.

**Comment by kosloot** [comment]
Aha, I see.
FoLiA-hocr uses the title attribute to create an ID for the FoLiA document is creates.
So it extracts "00529957.tif" from the title.
But xml:id may not start with a number. Yielding: XML error: '00529957.tif' is not a valid NCName.

This can be fixed rather easy. Some time next week....

**Comment by kosloot** [comment]
A fix is in GIT now. (also for FoLiA-pm)

**Comment by peterdekker** [comment]
Thanks! Is there, by any chance, a release planned, containing this fix, in the coming time? That would be nice, since I am using this tool as part of LaMachine in a production environment, which always pulls in the latest release.

**Comment by proycon** [comment]
v0.9(.1) was released last week, that should hopefully fix this issue.

**Comment by proycon** [comment]
Reopening this as this fix causes another bug: LanguageMachines/PICCL#30

**Comment by kosloot** [comment]
I don't think this is a bug. As FoLiA-hocr behaves well.
Just making up filenames (like appending 'id-' ) is always tricky.
But prefixing some, but not all output files is cumbersome too.

What do you suggest as a good prefix to always add? 'id-' ? ot 'fh-' or....

**Comment by proycon** [comment]
Or make the prefix configurable to I can pass it from PICCL, just as long as it's consistent for all it should be fine. Perhaps a default "hocr-" or something?

**Comment by kosloot** [comment]
ok, I added a --prefix option. The default is "FH-"

**Comment by proycon** [comment]
I'll test it in piccl context, we'll need a bugfix release then once it works

**Comment by proycon** [comment]
Works
