### ISSUE TITLE
FoLiA-correct can not handle custom text classes on the input side

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/foliautils#22]
This is a continuation of LanguageMachines/PICCL#34; ``FoLiA-correct`` seems hardcoded to use the OCR text class as input? Can we customize this with a new parameter? 

The same might also apply to other foliautils used by PICCL? Perhaps other ticcltools as well.

**Comment by kosloot** [comment]
Well, ticcltools are not FoLiA aware, so no problems there.
FoLiA-correct has the option --class to select the textclass.

In fact almost all FoLiA utils already have a --class option to set the textclass
FoLiA-alto, FoLiA-correct, FoLiA-hocr, FoLiA-langcat, FoLiA-stats, FoLiA-2text,
FoLiA-txt, FoLiA-idf, FoliA-page.

**Comment by kosloot** [comment]
Ah, I stand corrected. :) 
FoLiA-correct has indeed a --class option. But that is for output.
For input it isn't specified, which means it defaults to 'current'.

In the pipelines run by @martinreynaert this was never a problem.

I suggest adding a --inputclass parameter. (and rename--class to --outputclass ?)

**Comment by kosloot** [comment]
So the GIT version no knows about --inputclass.
I left --class as it is (for now) --outputclass would be preferable, I think.

**Comment by proycon** [comment]
> In the pipelines run by @martinreynaert this was never a problem.

Yeah, true, this was probably a feature I introduced myself without realising things weren't entirely prepared for it yet.

> So the GIT version no knows about --inputclass.
> I left --class as it is (for now) --outputclass would be preferable, I think.

Yes, agreed, better be explicit, at least in the ``--help``, but maybe keep the old one (unadvertised) for backward compatibility just in case.

**Comment by kosloot** [comment]
ok, --class is still accepted, but --outputclass is advertised, en preferred.
