### ISSUE TITLE
FoLiA-stats: not yet implemented mode

### ISSUE THREAD

**Issue by egpbos** [LanguageMachines/foliautils#24]
When running FoLiA-stats like

```sh
FoLiA-stats -o something some/folder/*.folia.xml
```
it gives the following output message:
```sh
start processing of XXX files
FoLiA-stats: not yet implemented mode:
```

Perhaps a slightly more helpful message could be printed. It seems the root cause in this case is the absence of "tags" (I am an absolute noob user, so I don't even know what this means at this point, I just [looked at the code here](https://github.com/LanguageMachines/foliautils/blob/75c3d895e80a5395714fa1db17981d90df6655fa/src/FoLiA-stats.cxx#L1457) and deduced the tags list must be empty). What would be the best way around this problem? An additional check for correct input options?

**Comment by kosloot** [comment]
Yeah, you are right. There is no 'default' mode or tag.
the `usage()` reveals that there are 2 modes implemented, and there is ""some" relation between those and the tags. 
But this is all quite obscure.
I think a better message is due, but also it may be wise to provide a reasonable default. but maybe that's the problem. @martinreynaert any opinions about that?

**Comment by pirolen** [comment]
Have experienced this too, then could run the tool with `FoLiA-stats --ngram 2 --tags='p' --class='OCR' ` on my usual example files. I see only unigram statistics (also tried --max-ngram). Anything else I could change?

**Comment by kosloot** [comment]
Hai @pirolen , 
Well, I tried it on the FoLiA-abby result of one of your test files, and it works like a charm:
```
,_S.	3
in_der	3
1,_S.	2
den_folgenden	2
der_Kaiserzeit	2
die_Dreifelderwirtschaft	2
folgenden_Erläuterungen	2
in_den	2
r._r.	2
```
Did you realize that the default separator for n-grams is a *underscore* ?
you can change it at as you like, e.g. with ``--separator=' '``
But if you are going to use more of the PICLL stack, it is preferred to use the underscore.

Unfortunate that @martinreynaert  didn't respond for almost 3 years :)

**Comment by pirolen** [comment]
Thanks a lot! I was looking at the wrong output file.
