### ISSUE TITLE
FoLiA-2txt : naming output files

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/foliautils#27]
For some reason FoLiA-2txt repeats the input file's full path after the path one specifies for -o. E.g.
instead of:
/reddata/VlaamsCorpus/OCR-T3/zzz/TXT/h36_brugge_3/h36_brugge_3-154.tif.folia.xml.txt
we get:
/reddata/VlaamsCorpus$ cat OCR-T3/zzz/TXT/h36_brugge_3/reddata/VlaamsCorpus/OCR-T3/zzz/FOLIA/h36_brugge_3/h36_brugge_3-154.tif.folia.xml.txt

**Comment by kosloot** [comment]
Right...
in fact it works as advertised, prepending the value of -o in front of all the outputfile names
But this works out not so well...
I suggest changing this in using only the **basename** of the input files to prepend.
So ``FoLiA-2text -o H36  /reddata/VlaamsCorpus/OCR-T3/zzz/FOLIA/h36_brugge_3/h36_brugge_3-154.tif.folia.xml`` 
will create ``H36/h36_brugge_3-154.tif.folia.xml.txt``
and not ``H36/reddata/VlaamsCorpus/OCR-T3/zzz/FOLIA/h36_brugge_3/h36_brugge_3-154.tif.folia.xml.txt``

**Comment by martinreynaert** [comment]
This would have the effect of possibly outputting the files from several different input to 1 directory. That is not desirable. In our case, we have three 'h36' files:
reynaert@black:/reddata/VlaamsCorpus$ ls -l Stemmen/StemmenuithetVerleden/Transcripties/h36*
-rwxr-xr-x 1 reynaert reynaert 1491689 Nov  1 12:40 Stemmen/StemmenuithetVerleden/Transcripties/h36_brugge_1.pdf
-rwxr-xr-x 1 reynaert reynaert 2018871 Nov  1 12:40 Stemmen/StemmenuithetVerleden/Transcripties/h36_brugge_2.pdf
-rwxr-xr-x 1 reynaert reynaert 2454640 Nov  1 12:40 Stemmen/StemmenuithetVerleden/Transcripties/h36_brugge_3.pdf

Please try to use the full name without the extension(s) as the name for the output directory as well as the basis for the output file (which is then given the extension .txt).

**Comment by kosloot** [comment]
This discussion is again getting VERY CONFUSING.
FoLiA-2txt doesn't work on .PDF files.
So please be more clear: What is the structure of the input. Are there really files in it with completely the same names?
To clarify my suggested solution:
Giving input files  ``/a/b/c/bla1.folia.xml /a/b/c/bla2.folia.xml /a/b/c/bla3.folia.xml``
running FoLiA-2text on them with -o OUT, the result would be to create 3 files:
`` OUT/bla1.folia.xml.txt OUT/bla2.folia.xml.txt OUT/bla3.folia.xml.txt``

Why is that a problem?

Your solution:
```
Please try to use the full name without the extension(s) as the name for the output directory as well as the basis for the output file (which is then given the extension .txt).
```
would mean that you want a file like ``/a/b/c/bla1.folia.xml `` to yield `` /a/b/c/bla1.folia.xml.txt``
so in the _same_ directory. This is quite feasible, and would just mean leaving the -o option out.
What at the moment is not allowed. But easily added.

**Comment by kosloot** [comment]
closing this due to lack of reactions
