### ISSUE TITLE
Error related to TextCat dependency

### ISSUE THREAD

**Issue by alankessler** [LanguageMachines/foliautils#28]
Is this related to #1? 

STDERR:

FoLiA-langcat.cxx: In function ‘int main(int, char**)’:
FoLiA-langcat.cxx:303:22: error: no matching function for call to ‘TextCat::TextCat(std::__cxx11::string&)’
   TextCat TC( config );
                      ^
In file included from FoLiA-langcat.cxx:48:0:
/home/arte/acme/include/ucto/my_textcat.h:49:3: note: candidate: TextCat
https://github.com/LanguageMachines/foliautils/issues/new::TextCat(const TextCat&)
   TextCat( const TextCat& );
   ^~~~~~~
/home/arte/acme/include/ucto/my_textcat.h:49:3: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const TextCat&’
/home/arte/acme/include/ucto/my_textcat.h:48:12: note: candidate: TextCat::TextCat(const string&, TiCC::LogStream*)
   explicit TextCat( const std::string&, TiCC::LogStream * );
            ^~~~~~~
/home/arte/acme/include/ucto/my_textcat.h:48:12: note:   candidate expects 2 arguments, 1 provided
make[2]: *** [FoLiA-langcat.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by proycon** [comment]
I'm experiencing the same problem, it is currently breaking the LaMachine development builds.

**Comment by kosloot** [comment]
I implemented a hasty fix in ucto. Hope this fixes it.

**Comment by kosloot** [comment]
Long story short: i implemented a new feature in ucto's TextCat (debugging) but broke backward compatibility. Now this should be fixed.

**Comment by alankessler** [comment]
Fixed :) thank you 
<img width="344" alt="image" src="https://user-images.githubusercontent.com/1541397/51056892-e86a3e80-1598-11e9-8046-d2e905142de1.png">
