### ISSUE TITLE
Saner defaults for FoLiA-stats?

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/foliautils#3]
FoLiA-stats doesn't work out of the box as expected because of the default values. I suggest `--lang none` and `--class current` as saner defaults.

**Comment by kosloot** [comment]
I totally agree. But breaking this might hurt TiCCL and such, so I would suggest to consult
@martinreynaert on this issue.

**Comment by proycon** [comment]
I guess ticcl should just explicitly set the parameters, we'll have to talk to @martinreynaert  :)

**Comment by martinreynaert** [comment]
I am in favour of saner defaults. PICCL will just have to be adapted to them if need be.

**Comment by kosloot** [comment]
Done
