### ISSUE TITLE
use the 'hemp' algorithm in FoLiA-correct to solve Historical Emphasis

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/foliautils#30]
FoLiA-stats generates a 'hemp' file containing Historical Emphasis like:
``N_A_P_O_L_E_O_N``
Which is the emphasized form of Napoleon.
Of course there will bet variants too:
``N_AP_O_LE_ON`` etc.

We could (some magic involved) use the TICLL tools to generate a translation list of these `emp` words:
```
N_A_P_O_L_E_O_N  Napoleon
N_AP_O_LE_ON     Napoleon
```
etc.

When running FoLiA-correct, we then can use the same hemp-detector as FoLiA-stats has to (again) find these 'words' and directly replace them using the translation list.
Probably BEFORE applying other n-gram corrections?

**Comment by martinreynaert** [comment]
Yes indeed, it seems absolutely logical to perform this correction step first.

**Comment by martinreynaert** [comment]
We here draw up a 'plan' to start activating the hemp file information as provided by FoLiA-stats in TICCL as a whole.

TICCL-unk should incorporate the items from the hemp file, if the latter is present, for it is optional. It should list each item followed by its cleaned version in its punct file. This in the first instance entails filtering out the spaces as represented by default by an underscore or '_'. Further, the usual cleaning, i.e. removing word-external punctuation as currently implemented in TICCL-unk. The cleaned versions are then also added to the *clean list, as is currently any other cleaned word form. Each 'hemp' cleaned word form will add a frequency of 1 to the clean list frequency (the hemp file does not currently have frequency information, we do not consider this important, we will treat them all as hapaxes, as the bulk of them probably will be).

Further TICCL processing can then proceed as it is currently, the 'hemp' items need no further special treatment until we will want to actually edit the texts with FoLiA-correct. For a sliding windows of three items from the text to be corrected, FoLiA-correct currently checks the punct file first for the 'unclean' word trigram. If there is a match, it picks up the clean version of the trigram from the right-hand column of the punct file and checks in the ranked file (or derivation: chained of chained.cleaned file) if a correction candidate is present. If not, it checks whether perhaps the ranked file offers a correction candidate for the already presumably clean trigram as extracted from the text to be corrected.  If this fails, this is repeated for both bigrams in the trigram and the three unigrams in the trigram. Upon completion the three item window slides further over the text, in the appropriate fashion based on the actual outcomes of the tri-, bi-, unigram lookups. Note that the foregoing lines describe how we understand FoLiA correct currently operates.

Now we think that given that we do not allow trigrams based on too short words to be incorporated in the clean list to start with, if the trigram is a sequence of three very short words (typically single characters), this should be sufficient to trigger look-up for 'hemp'-items. Perhaps at this point, in FoLiA-correct, the trigram might then be instantly expanded in line with the algorithm used in FoliA-stats today to identify these hemp items in the first place. This whole larger ngram might then be replaced by the solution as offered for the cleaned string in the ranked file.

We hope some variant of the above will prove implementable. We look forward to being able to recover extremely split words from texts!

**Comment by kosloot** [comment]
So leaving all side-notes aside, the question boils down to:
``
It should list each item followed by its cleaned version in its punct file. This in the first instance entails filtering out the spaces as represented by default by an underscore or '_'. Further, the usual cleaning, i.e. removing word-external punctuation as currently implemented in TICCL-unk. The cleaned versions are then also added to the *clean list, as is currently any other cleaned word form.``

To be sure, lets take as an example, the hemp: `F_1_o_r_e_n_t_ij_n_e_r.`

The 'space-free' variant would be: `F1orentijner.` So the idea is:
- add `F_1_o_r_e_n_t_ij_n_e_r.    F1orentijner` to the punct file. (removing the final punctuation)
- add `F1orentijner   1` to the clean list

**Comment by martinreynaert** [comment]
That is indeed the first step.

FoLiA-correct will still have to be extended to properly deal with these cases, though.

Thanks!

**Comment by kosloot** [comment]
Ok, some follow-up questions.
1. I assume we use a frequency of 1, NOT  (1 + artifreq) (as for background words)
2. How to handle NOT punctuated words: like: ``F_1_o_r_e_n_t_ij_n_e_r``
Do we add them only to *clean or also to punct?
yieiding:
``F1orentijner    1``
and
``F_1_o_r_e_n_t_ij_n_e_r     F1orentijner``
respectively?

**Comment by martinreynaert** [comment]
We try to remove the complications raised by 'hemp' cases as far as possible, on the earliest possible occasion. That is in TICCL-unk.

1. Sure, we are not going to 'validate' a 'clean' form such as 'F1orentijner' by adding the artifrq.

Anyway, I was assuming we always add the frequency of a cleaned word form, i.e. a word form relieved of initial or final punctuation, to its observed frequency as a clean form (regardless of whether this got the artifrq on top of that or not).

2. Non-punctuated hemp forms, i.e. strings containing more than two spaces/underscores,  are not to be added to *clean, in contrast to the way we handle bi- and trigrams. Their cleaned forms are, observing the above as concerns frequency.

Unlike bi- and trigrams, multi-underscored forms are not to be added to *clean in order to avoid unnecessary complication of anagram retrieval of variants and Levenshtein distance calculations, let alone, subword frequency issues. 

The multi-underscored forms are to be added to *punct, in order for FoLiA-correct later to able to identify them and to be able to retrieve possible corrected forms from *ranked(.chained/.chained.cleaned).

Hope this clarifies matters!

**Comment by kosloot** [comment]
``Hope this clarifies matters!``
Not really, as you add more obfuscation, imho.

Simplest answer would have been:
1 YES
2 YES.

Regarding 2:
I DID NOTsuggest to add the hemp form to be added to *CLEAN, but whether it should be added tot *PUNCT, (as in the punctuated case.) In your last remark you seem to acknowledge this.

A test version will appear on violet immanent.

**Comment by kosloot** [comment]
I never received feedback. I suggest to move on and deploy this to black  too.
or maize, as soon as I have access
