### ISSUE TITLE
FoLiA-abby for ABBYY Finereader 11 (Linux) version output

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/foliautils#31]
FoLiA-abby was developed on the basis of ABBYY output from the CLARIAH pilot project OpenGazAm. This worked as expected, as far as we are aware today.

In CLARIAH pilot project CCC:DB ABBYY Finereader 11 for Linux was used, which is another OCR-engine from the same stable. This produces different output and FoLiA-abby cannot yet handle this well.

An example:

```xml
      <p xml:id="ABBYYtoFOLIAlevi010geil01_01_Deel493.xml.gz.text.div1.p2">
         <part xml:id="ABBYYtoFOLIAlevi010geil01_01_Deel493.xml.gz.text.div1.p2.entry">
           <t class="OCR">gevonden.MetnieuwenmoedtrokhijnaarhetVaalgebied, dochwedertevergeefs.</t>
        </part>
```

Current output lacks spaces between the words and in at least one instance we have seen words in slightly different variants repeated.

Finereader produces a range of alternatives for each character and for each word, it seems. I take it they are ordered in descending order of probability, but cannot be sure about this. 

When we grep on an output file:

reynaert@red:/reddata/PILOTS/DIABOR$ cat /reddata/PILOTS/DIABOR/OCR/levi010geil01_01_Deel500.xml |grep 'Variants'

This also tells you the location of our ABBYY Finereader 11 output. Current output of FoLiA-abby is in:

/reddata/PILOTS/DIABOR/ABBYYtoFOLIA/

We find in this 'grep':

```xml
<wordRecVariants>
<charRecVariants>
</charRecVariants>k</charParams><charParams l="661" t="2736" r="684" b="2770" charConfidence="78" serifProbability="255">
<charRecVariants>
</charRecVariants>o</charParams><charParams l="661" t="2736" r="684" b="2770" charConfidence="100" serifProbability="0">
<charRecVariants>
</charRecVariants>n</charParams>
<charRecVariants>
</charRecVariants>k</charParams><charParams l="661" t="2736" r="684" b="2770" charConfidence="78" serifProbability="255">
<charRecVariants>
</charRecVariants>o</charParams><charParams l="661" t="2736" r="684" b="2770" charConfidence="100" serifProbability="0">
<charRecVariants>
</charRecVariants>n</charParams>
</wordRecVariants>
<charRecVariants>
</charRecVariants>k</charParams>
<charRecVariants>
</charRecVariants>o</charParams>
<charRecVariants>
</charRecVariants>n</charParams>
<charRecVariants>
</charRecVariants> </charParams>
<wordRecVariants>
```

We see the word 'kon' repeated 3 times. The last time, no attributes are given, we take this to be Finereader's 'decision' about the word. This is also followed by the 'missing' space.

Hope this helps to adjust FoLiA-abby (the name is actually spelled with a double 'y') to Finereader 11 output!

**Comment by kosloot** [comment]
@martinreynaert A new implementation of FoLiA-abby is put on violet for testing purposes.
It should handle this kind of files much better. Please test, and let me know when there are still issues.

**Comment by kosloot** [comment]
seems ok. closing issue
