### ISSUE TITLE
FoLiA-2text aborts on a metadata issue

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/foliautils#37]
This happened on the Staten-Generaal Digitaal FoLiA which has been been processed by just about every other FoLiA tool before.

[1]+  Aborted                 nohup /exp/sloot/usr/local/bin/FoLiA-2text -t 120 --class=Ticcl -e ticcl.xml -o /reddata/POLMASH/FOLIALangCatTICCLTXT/d/nl/proc/sgd/ /reddata/POLMASH/FOLIALangCatTICCL/d/nl/proc/sgd/ > /reddata/POLMASH/FOLIALangCatTICCLTXT.sgd.20191112.stdout 2> /reddata/POLMASH/FOLIALangCatTICCLTXT.sgd.20191112.stderr

reynaert@maize:/reddata/POLMASH$ cat /reddata/POLMASH/FOLIALangCatTICCLTXT.sgd.20191112.stderr
nohup: ignoring input
WARNING: foreign-data found in metadata of type 'native'
changing type to 'foreign'
WARNING: foreign-data found in metadata of type 'native'
changing type to 'foreign'
WARNING: foreign-data found in metadata of type 'native'
changing type to 'foreign'
terminate called recursively
terminate called after throwing an instance of 'folia::NoSuchText'
reynaert@maize:/reddata/POLMASH$

I have no idea.

**Comment by martinreynaert** [comment]
Addendum:

Before it crashed it created 5 output files, one of which had actual output:

reynaert@maize:~$ ls -l /reddata/POLMASH/FOLIALangCatTICCLTXT/d/nl/proc/sgd/
total 2
-rw-r--r-- 1 reynaert reynaert    0 Nov 12 16:41 nl.proc.sgd.d.186918700000115.folia.lc.ticcl.xml.txt
-rw-r--r-- 1 reynaert reynaert    0 Nov 12 16:41 nl.proc.sgd.d.189618970000236.folia.lc.ticcl.xml.txt
-rw-r--r-- 1 reynaert reynaert    0 Nov 12 16:41 nl.proc.sgd.d.190419050000115.folia.lc.ticcl.xml.txt
-rw-r--r-- 1 reynaert reynaert    0 Nov 12 16:41 nl.proc.sgd.d.195419550000051.2.folia.lc.ticcl.xml.txt
-rw-r--r-- 1 reynaert reynaert 1398 Nov 12 16:41 nl.proc.sgd.d.198819890000898.8.folia.lc.ticcl.xml.txt

Before this run, I tested it on a small number of files and it ran as expected.

**Comment by kosloot** [comment]
Well, this is caused by running FoLiA-2text on files without any text in it.
This was not foreseen :{
I commited a patch to skip such documents.
