### ISSUE TITLE
FoLiA-correct cannot be run twice on same file

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/foliautils#38]
We discussed this last week in IRC and the conclusion was that this should be a bug.

I would like to run FoLiA-correct twice over the same file, using different input files and outputting to a new, separate --outputclass.

This currently does not work. What I tried was this (starting from empty output directories):

reynaert@violet:/reddata/NA/proto/FOLIA/TICCL$ /exp/sloot/usr/local/bin/FoLiA-correct -t 2 --inputclass HTR --outputclass TICCLA --nums 1 --ngram 2 -e folia.xml -O /reddata/NA/proto/FOLIA/TICCL/TRAPTEST/FOLIAcorrect/ --unk /reddata/NA/proto/FOLIA/TICCL/NAK.wordfreqlist.1to2.tsv.CLEAN.unk --punct /reddata/NA/proto/FOLIA/TICCL/NAK.wordfreqlist.1to2.tsv.CLEAN.punct --rank NAK.wordfreqlist.1to2.tsv.CLEAN.clean.ANAHASH.anahash.INDEXER.index.LDCALC.ldcalc.RANK.ranked.CHAIN.REVERSEDSELECTION.underscoretoplusminus.chained /reddata/NA/proto/FOLIA/TICCL/TRAPTEST/FOLIA >TRAPTEST.20191107.UNRIGGED.stdout 2>TRAPTEST.20191107.UNRIGGED.stderr

reynaert@violet:/reddata/NA/proto/FOLIA/TICCL$ ls -l /reddata/NA/proto/FOLIA/TICCL/TRAPTEST/FOLIAcorrect/
total 64
-rw-r--r-- 1 reynaert reynaert 64575 Nov  7 22:56 NL-HlmNHA_1972_469_0527.xml.ticcl.folia.xml

reynaert@violet:/reddata/NA/proto/FOLIA/TICCL$ /exp/sloot/usr/local/bin/FoLiA-correct --setname="Ticcl2-set" -t 2 --inputclass TICCLA --outputclass TICCLB --nums 1 --ngram 2 -e folia.xml -O /reddata/NA/proto/FOLIA/TICCL/TRAPTEST/FOLIAcorrectB/ --unk /reddata/NA/proto/FOLIA/TICCL/NAK.wordfreqlist.1to2.tsv.CLEAN.unk --punct /reddata/NA/proto/FOLIA/TICCL/NAK.wordfreqlist.1to2.tsv.CLEAN.punct --rank /reddata/NA/proto/FOLIA/TICCL/NAK.wordfreqlist.1to2.tsv.CLEAN.clean.ANAHASH.anahash.INDEXER.index.LDCALC.ldcalc.RANK.ranked.CHAIN.UnderscoreToPlusmin.chained /reddata/NA/proto/FOLIA/TICCL/TRAPTEST/FOLIAcorrect/ >TRAPTESTB.20191107.UNRIGGED.stdout 2>TRAPTESTB.20191107.UNRIGGED.stderr

reynaert@violet:/reddata/NA/proto/FOLIA/TICCL$ ls -l /reddata/NA/proto/FOLIA/TICCL/TRAPTEST/FOLIAcorrectB/
total 0
-rw-r--r-- 1 reynaert reynaert 0 Nov  7 22:57 NL-HlmNHA_1972_469_0527.xml.ticcl.ticcl.folia.xml

reynaert@violet:/reddata/NA/proto/FOLIA/TICCL$ mkdir /reddata/NA/proto/FOLIA/TICCL/TRAPTEST/FOLIAcorrectBclear

reynaert@violet:/reddata/NA/proto/FOLIA/TICCL$ /exp/sloot/usr/local/bin/FoLiA-correct --setname="Ticcl2-set" --clear -t 2 --inputclass TICCLA --outputclass TICCLB --nums 1 --ngram 2 -e folia.xml -O /reddata/NA/proto/FOLIA/TICCL/TRAPTEST/FOLIAcorrectBclear --unk /reddata/NA/proto/FOLIA/TICCL/NAK.wordfreqlist.1to2.tsv.CLEAN.unk --punct /reddata/NA/proto/FOLIA/TICCL/NAK.wordfreqlist.1to2.tsv.CLEAN.punct --rank /reddata/NA/proto/FOLIA/TICCL/NAK.wordfreqlist.1to2.tsv.CLEAN.clean.ANAHASH.anahash.INDEXER.index.LDCALC.ldcalc.RANK.ranked.CHAIN.UnderscoreToPlusmin.chained /reddata/NA/proto/FOLIA/TICCL/TRAPTEST/FOLIAcorrect/ >TRAPTESTB.20191107.UNRIGGED.clear.stdout 2>TRAPTESTB.20191107.UNRIGGED.clear.stderr

reynaert@violet:/reddata/NA/proto/FOLIA/TICCL$ ls -l /reddata/NA/proto/FOLIA/TICCL/TRAPTEST/FOLIAcorrectBclear/
total 0
-rw-r--r-- 1 reynaert reynaert 0 Nov  7 22:59 NL-HlmNHA_1972_469_0527.xml.ticcl.ticcl.folia.xml

reynaert@violet:/reddata/NA/proto/FOLIA/TICCL$ history >UNRIGGED.unsuccessful.20191107.hist

I want to use this for another purpose too, after which I will need a functioning FoLiA-2text.

**Comment by kosloot** [comment]
running FoLiA-correct multiple times should definitely work, when a new outputclass is selected.
I will have to investigate this further, to find out if it's a problem with FoLiA-correct or deeper in the folia library.

**Comment by kosloot** [comment]
Ok, I needed to patch libfolia to solve this.
A new version is installed on violet and maize now.
Please test!

**Comment by martinreynaert** [comment]
I do not seem able to make this work. I have put the documentation for this in long mail. Subject = TICCL: Running FoLiA-correct twice: cannot make it work

Whatever I try (variations of -ngram=1 or =2 and with or without --clear all produce empty output files.

**Comment by kosloot** [comment]
This was due to a missing --setname option, I assume

**Comment by martinreynaert** [comment]
Affirmative. Missing --setname option *and* missing --clear option, actually.

**Comment by martinreynaert** [comment]
I close this issue and open a new related.
