### ISSUE TITLE
Optional output option for FoLiA-correct

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/foliautils#39]
In order to be able to preserve the one-to-one alignment between original and (possibly) multiple TICCL correction text classes on the paragraph level, I would optionally like FoLiA-correct to output another character than a regular space character when working with the *punct file.

My optional character for now would be the plus-minus sign '±'.

**Comment by kosloot** [comment]
This is implemented now. using the ``--punctseparator`` option
