### ISSUE TITLE
question on using XML_PARSE_HUGE

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/foliautils#44]
Sebastian Pipping: @hartwork  posted an e-mail questioning the (dangerous) use of XML_PARSE_HUGE:

```
I ran into your commit [1] using XML_PARSE_HUGE option of libxml2.

I am looking for files that hit related limits with libxml2 in context
of research about billion laughs attacks to add sound protection against
those to libexpat by the end of 2020.
Do you you remember why you added XML_PARSE_HUGE?  Do you have files
that run into libxml2 limits or know anyone dealing with "extreme XML
files" that you can can connect me to?
```

The billion of laughs is a know way to make XML parsers explode: https://en.wikipedia.org/wiki/Billion_laughs_attack

**Comment by kosloot** [comment]
So We are aware of the vulnerability, but as I answered @hartwork:
```
 All the software for FoLiA is used in a very special, scientific
research, context so abuse is, although possible, not really an issue
for us.
We take the risk that someone launches a billion laughs attack.

More important for us is, to get the work done on files that DO exist an
lead to very large parses. (a 1.1 G file will expand to 24 G in memory,
and we DO have examples)

But now i start wondering: Why would you modify foliautils? Do you have
a special need for it?
We don't mind living in danger 
```
to add: In the closed approach we have, huge files containing linguistic data are created and processed. 
Most of the process is automated, and creating a toxic file is not easy.

So I don't see the need to modify our code (and that of https://github.com/LanguageMachines/libfolia/ ) at the moment.

@martinreynaert may I provide @hartwork with a large example folia file from your data?
I found one already that is 1.1Gb big but I think there are even bigger ones.

**Comment by kosloot** [comment]
@hartwork I will send you in a PM an XML file that our software is able to handle, but that fails without the XMP_PARSE_HUGE setting.
The message being: 
```
dpo.1321.book.1784.folia.xml:2379868: XML-error: ID dpo.1321.mpeg21.0265.alto.text.p.TextBlock12.String946 already defined
```
(the internal libxml2 id counter probably overflows)

To test this you need some memory.... at least 24 G.
I even have a larger example but that didn't fit in my  32G system.

NOTE: Of course we could have tried using other solutions, without constructing a complete DOM tree in memory.
Part of our software does so using XmlReader, but still the indexes would overflow and PARSE_HUGE is needed.

Using SAX (or expat) is left as an exercise :)

**Comment by hartwork** [comment]
> (the internal libxml2 id counter probably overflows)

Wow! Could be a bug.

**Comment by kosloot** [comment]
Well, it uses arrays of size 'short int' or maybe 'int' which overflows. PARSE_HUGE overcomes that.
And  the xmlNode 'linenumber' member is a short int, which is rather clumsy.

Fixing would break the ABI a assume.

**Comment by kosloot** [comment]
Closing this, as this is NOT a libfolia bug. (but a feature)
