### ISSUE TITLE
does FoLiA-benchmark a good job?

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/foliautils#48]
in line 207, FoLiA-benchmark selects all the Word* 's of a Document.
But the result is never used!
I assume the compiler will optimize this selection away, making this test overly optimistic about the speed. 

This could be fixed by using the selection in for instance an output statement telling it's size.

**Comment by proycon** [comment]
Hmm, good point, I may have forgotten to take compiler optimisation into account there.
