### ISSUE TITLE
FoLiA-page will fail if no filename is found in the metadata

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/foliautils#49]
FoLiA-page assumes that the name of thee original scanned document is stored in the metadata.
This is not always the case (see attached example)
[0001.xml.txt](https://github.com/LanguageMachines/foliautils/files/5547568/0001.xml.txt)
This name is used to generate an FoLiA output file-name.

A quick fix would be to use the name of the page file as a template for the output name.

**Comment by pirolen** [comment]
The output file originates from OCR4all with default settings.
Thanks!

**Comment by kosloot** [comment]
This input-file lacks some more information that FoliA-page assumes to be present.
So it needs some time and thinking to come up with a solution that doesn't bail out on missing, (and probably non-essential,) elements. Like using sane defaults. Stay tuned.

**Comment by kosloot** [comment]
@pirolen Unfortunately the PAGE output from OCR4all is quite different from the versions where FoLiA-page is based on.
So a total rework has to be done. This will not be possible in the coming week or so. It is a nice improvement though.

**Comment by pirolen** [comment]
Sure! Thanks! Meanwhile, I have another PAGE XML, from Transkribus (with defaults -- might get more complete -- under testing), please find attached.
[roemische_1pg.xml.txt](https://github.com/LanguageMachines/foliautils/files/5559309/roemische_1pg.xml.txt)

**Comment by kosloot** [comment]
thanx. I will use that second file for further improvements.

**Comment by martinreynaert** [comment]
[https://ticclops.uvt.nl/NL-HaNA_1.05.01.02_333_0156.xml](url)

Above is the link to a Dutch National Archives Transkribus-produced page-file on which FoLiA-page currently fails. There is no filename in the metadata. I am very interested on seeing this solved as I happen to have 3 million of these files.
Great to see other people want to use FoLiA-page as well!!

**Comment by kosloot** [comment]
All issues are solved in the upcoming release

**Comment by martinreynaert** [comment]
Hi Ko, Thanks!

I now have a 'dev' version of LaMachine on my server. And the problem seems solved for single files. So I now tried to run it on a relatively small dir of these PAGE-files and basically the same issue is reported again in my stderr. Also the program was aborted due to an empty text element in (at least) one of the PAGE xml files. I give the output on that one first:
(LMdev) reynaert@violet:~$ FoLiA-page -t 1 --class=HTR -O /reddata/NATAR/PAGE/WIcom/FOLIA /reddata/NATAR/PAGE/WIcom/UNZIP/NL-HaNA_2.01.28.01_170_0480.xml |grep '><'
terminate called after throwing an instance of 'folia::ValueError'
  what():  TextContent: 'value' attribute may not be empty.
The last <Unicode> element in this input file indeed is empty.
I hope this can somehow be solved on the fly...

The command that gave failure on the dir of PAGE files was this:
(LMdev) reynaert@violet:~$ nohup /exp/sloot/usr/local/bin/FoLiA-page -t 100 --class=HTR -O /reddata/NATAR/PAGE/WIcom/FOLIA /reddata/NATAR/PAGE/WIcom/UNZIP/ >/reddata/NATAR/PAGE/WIcom/WIcomPAGEtoFOLIA.20201212.bis.stdout 2>/reddata/NATAR/PAGE/WIcom/WIcomPAGEtoFOLIA.20201212.bis.stderr &

The tail of my stderr file after breakdown reads:
(LMdev) reynaert@violet:~$ cat /reddata/NATAR/PAGE/WIcom/WIcomPAGEtoFOLIA.20201212.bis.stderr |tail -n 5
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP//NL-HaNA_2.01.28.01_108_0270.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP//NL-HaNA_2.01.28.01_108_0270.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP//NL-HaNA_2.01.28.01_170_0480.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP//NL-HaNA_2.01.28.01_170_0480.xml
free(): double free detected in tcache 2

**Comment by martinreynaert** [comment]
[100.zip](https://github.com/LanguageMachines/foliautils/files/5680054/100.zip)

Small test sample to reproduce the problem:

(LMdev) reynaert@violet:UNZIP$ nohup /exp/sloot/usr/local/bin/FoLiA-page -t 6 --class=HTR -O /reddata/NATAR/PAGE/WIcom/FOLIA/TEST /reddata/NATAR/PAGE/WIcom/UNZIP/TEST >/reddata/NATAR/PAGE/WIcom/WIcomPAGEtoFOLIA.20201212.TEST100zip.stdout 2>/reddata/NATAR/PAGE/WIcom/WIcomPAGEtoFOLIA.20201212.TEST100zip.stderr &
[1] 16695
(LMdev) reynaert@violet:UNZIP$ 
[1]+  Aborted                 nohup /exp/sloot/usr/local/bin/FoLiA-page -t 6 --class=HTR -O /reddata/NATAR/PAGE/WIcom/FOLIA/TEST /reddata/NATAR/PAGE/WIcom/UNZIP/TEST > /reddata/NATAR/PAGE/WIcom/WIcomPAGEtoFOLIA.20201212.TEST100zip.stdout 2> /reddata/NATAR/PAGE/WIcom/WIcomPAGEtoFOLIA.20201212.TEST100zip.stderr
(LMdev) reynaert@violet:UNZIP$ cat /reddata/NATAR/PAGE/WIcom/WIcomPAGEtoFOLIA.20201212.TEST100zip.stderr
nohup: ignoring input
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0003.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0003.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0015.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0015.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0021.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0021.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0016.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0016.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0024.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0024.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0002.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0002.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0009.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0009.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0008.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0008.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0001.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0001.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0019.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0019.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0022.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0022.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0014.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0014.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0012.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0012.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0017.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0017.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0006.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0006.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0023.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0023.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0010.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0010.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0011.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0011.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0004.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0004.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0018.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0018.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0005.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0005.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0020.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0020.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0013.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0013.xml
unable to retrieve an original filename from /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0007.xml
failure on /reddata/NATAR/PAGE/WIcom/UNZIP/TEST/NL-HaNA_2.01.28.01_100_0007.xml
free(): double free detected in tcache 2
(LMdev) reynaert@violet:UNZIP$ ls -l 100.zip
-rw-r--r-- 1 reynaert reynaert 810538 Oct 21 21:03 100.zip
(LMdev) reynaert@violet:UNZIP$ cp 100.zip /home/reynaert

**Comment by kosloot** [comment]
further, let me point out that you are NOT running the LaMachine version of the software!!!
```(LMdev) reynaert@violet:UNZIP$ nohup /exp/sloot/usr/local/bin/FoLiA-page -t 6 --class=HTR -O ```

**Comment by martinreynaert** [comment]
I stand corrected and apologise for the red herring! I inadvertently copied part of an older command line and there explicitly called on the older version of FoLiA-page on my server instead of on the development version one of LaMachine, in which I was operating.

**Comment by martinreynaert** [comment]
!nice

(LMdev) reynaert@violet:PAGE$ 
[2]+  Done                    nohup FoLiA-page -t 111 --prefix= NA_ --class=HTR -O /reddata/NATAR/PAGE/WIC1/FOLIA /reddata/NATAR/PAGE/WIC1/UNZIP/ > /reddata/NATAR/PAGE/WIC1/WIC1.PAGEtoFOLIA.20201212.stdout 2> /reddata/NATAR/PAGE/WIC1/WIC1.PAGEtoFOLIA.20201212.stderr

(LMdev) reynaert@violet:PAGE$ ls -l /reddata/NATAR/PAGE/WIC1/FOLIA |wc
  45028  405245 4346111

Time: from: 14:57 to: 15:00, i.e. in 3 minutes.

FoLiA-page seems to have gained a lot of robustness! Thanks!
