### ISSUE TITLE
FoLiA-langcat should handle text in <head> nodes too

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/foliautils#5]
Head may contain (long) texts, where language detection can be useful.

Question: should we always do this? Or yet another switch?

**Comment by kosloot** [comment]
implemented a --tags option now.
--tags=s,head,note will examine text under 's', 'head' and 'note' nodes respectively and language tags will be assigned when possible.

Note to @JessedeDoes : --tags=t will work too, but needs an update of libfolia. 

Please test!

**Comment by JessedeDoes** [comment]
Zojuist eerste batch Huygens-corpora gedraaid met nieuwe versie.
De optie met --tags=t werkt in ieder geval prima, zo te zien.

Bedankt!
