### ISSUE TITLE
FoLiA-abby: add font style information

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/foliautils#51]
@pirolen wrote:
yesterday I run FoLiA-abby in LaMachine (foliautils 0.15), with success! 
Impressive. This tool enables me to use Abbyy’s own XML output directly from its Finereader Engine.  

Just that, I would need the font style information, which is present in the Abbyy XML, but does not seem to be propagated to the FoLiA document.

These would be Text Markup Annotations I believe, such as style-annotation (e.g. <t-style class="italic”>) and (if possible) Hyphenation (<t-hbr>).

**Comment by pirolen** [comment]
Thank you so much! I attach an example file with Abbyy-XML, where font style information is present.

[b1_2_kap4_p297_img_png_out_abbyy_deu.xml.txt](https://github.com/LanguageMachines/foliautils/files/5651630/b1_2_kap4_p297_img_png_out_abbyy_deu.xml.txt)

**Comment by pirolen** [comment]
The XSD schema of the output file is possibly:
https://www.ocrsdk.com/schema/resultDescription-1.0.xsd

**Comment by kosloot** [comment]
I improved FoLiA-abby to include style and hbr information.
Probably not perfect yet.

**Comment by kosloot** [comment]
Now I also added the paragraphStyles tot the metadata, and the referring ID's to the style markup.
The file you provided now yields this: 
[FA-piroska.abby.folia.xml.txt](https://github.com/LanguageMachines/foliautils/files/5775919/FA-piroska.abby.folia.xml.txt)

**Comment by proycon** [comment]
Looks good to me. Nice example of using foreign metadata.

For completion's sake: the foreign metadata is obviously foreign to FoLiA, so whatever relations are assumed between the t-style classes and the foreign metadata is a matter of convention rather than formalism. The same applies to the use of ``|`` to seperate classes, which has no formal semantics for FoLiA. If you want to really list all possible classes for a set or feature subset (which is something FLAT makes use of), you need an actual FoLiA set definition.

**Comment by kosloot** [comment]
Yes, the "reference" is just a convention.
Note that "normal" \<t\> nodes are missing these, as for some reason it is forbidden to add \<feature\> nodes to a \<t\>
I would plea to allow this.
Side note: Would a \<t-ref\> be a better choice here, or even worse?

Considering the '|': 
That could be defined in a "FoLiA-abby-set".
There is a limited amount of combinations possible, so just summing them up is doable.

**Comment by pirolen** [comment]
Many thanks, this enhancement is awesome! 

Note: font size, i.e. the "fs" attribute in Abbyy XML, is a property that all characters have, and it would be great to have it directly included for the relevant text portions, if possible -- (maybe by using the  '|' where applicable), and then also the "normal" (that is, so far style-less?) <t> nodes would always have a t-style?

**Comment by pirolen** [comment]
Minor detail: there are two types of end-of-line characters used by Abbyy, the normal hyphen and a '¬'. It's [number 172 in extended ASCII](https://www.petefreitag.com/cheatsheets/ascii-codes/), but is probably unexpected as they seem not be represented in the converted files. It would be nice to convert these characters to a hyphenised break.

**Comment by kosloot** [comment]
Ok , the  '¬'. was deliberately left out. But replacing it by \<t-hbr/\> is maybe better.

I also added the font size. But using the '|' trick feels uncomfortable now.  ( and it would create a problem defining a FoLiA-abby set)
Therefore I added it as a feature now.
see: [FA-piroska.abby.folia.xml.2.txt](https://github.com/LanguageMachines/foliautils/files/5777919/FA-piroska.abby.folia.xml.2.txt)

**Comment by pirolen** [comment]
Ah OK, thanks! 
Still, not all text parts have the font size feature (e.g.:  `<t class="OCR">Grundherrschaften der Kaiserzeit </t>`). but  maybe only those have it that have a t-style element as well? Would it be possible that all text parts have the font size feature?

**Comment by kosloot** [comment]
I would prefer that, and suggested to @proycon  but he didn't respond yet. It requires a small change in the definitions to allow for features under a \<t\>

**Comment by proycon** [comment]
I agree with allowing \<feat\> under \<t\> yes, and have already done some commits to that end. But I'd still recommend to wrap the whole text in a \<t-style\>, just to be more semantically accurate.

**Comment by kosloot** [comment]
Ok, I think everything is settled now. The new FoLiA-abby has been released

**Comment by pirolen** [comment]
Thanks!! Does it suffice to update only languagemachines-basic?

**Comment by proycon** [comment]
Yes, that should be sufficient

**Comment by pirolen** [comment]
Great, works like a charm 👍  Many thanks for implementing all of what this enhancement took! 🥇

**Comment by pirolen** [comment]
Ah, one more question: 
in the Abbyy XML there are the `paragraphStyle id=` elements (thankfully propagated to the foreign metadata in the FoLiA-files). These style IDs are later pointed to from the Abbyy XML, e.g.
`<text>
<par align="Justified" lineSpacing="1289" style="{2EC5537B-6378-40BF-9D61-FD87FAF8774E}"> ...`.
Do you think these style ID references could also be propagated to the FoLiA files? E.g.  as 'feat class="{...}" subset="par_style"/>'?

**Comment by kosloot** [comment]
Sounds doable. Will look into that.

**Comment by kosloot** [comment]
Now implemented, available form github and inLlaMachine-dev soon(ish?)

**Comment by proycon** [comment]
(availability from the development lamachine is always direct and requires no intervention my part, it simply grabs the latest git master branch by definition)

**Comment by pirolen** [comment]
> Now implemented

Cool, thanks! 
Could these subsets be named something like 'par_style'? Now they are called "font_id" (which is kind of taken already for fontStyle ids), but they designate paragraphStyle ids.

**Comment by kosloot** [comment]
I don't mind changing the name, as it is 'just a convention' but I would like to have this settled once we start spreading the software.
looking at this fragment:
```xml
        <paragraphStyle id="{8196C26E-7010-43B2-9E10-63A3142A79C9}" name="Other|1" mainFontStyleId="{307674DC-676D-4083-84B2-77156A007C47}" role="other" align="Left" startIndent="0" leftIndent="0" rightIndent="0" lineSpacing="1284" fixedLineSpacing="0">
          <fontStyle id="{307674DC-676D-4083-84B2-77156A007C47}" baseFont="1" ff="Times New Roman" fs="11." backgroundColor="4278190079"/>
          <fontStyle id="{8163B20A-5CB5-4784-9915-7B6DB3E8988F}" ff="Times New Roman" fs="10." backgroundColor="4278190079"/>
          <fontStyle id="{72CFDA41-3865-4EB2-A00D-0565CA4F2BD7}" ff="Arial" fs="6." backgroundColor="4278190079"/>
        </paragraphStyle>

```

'par_style' seems a good name. But maybe 'font_id' is better called 'font_style' then?
just my 2 ¢

**Comment by pirolen** [comment]
I would be fine with a naming that is FoLiA-ic enough, and distinguishes between these two. (We could also use paragraphStyle and fontStyle, if camel case is OK, etc.)

**Comment by kosloot** [comment]
Ok, I choose par_style and font_style then 
Submitted to Git

**Comment by pirolen** [comment]
> But using the '|' trick feels uncomfortable now. ( and it would create a problem defining a FoLiA-abby set)

I still see the '|' trick being used, is that meant to be used?  (I am pasting an example at the end inline).

These multiple font style infos seem not be rendered by folia2html.
Not sure if I should co-reference it with
https://github.com/proycon/foliatools/issues/26



`
 <t class="OCR">
            <t-style class="italic|superscript"><feat class="{8FCDDF9A-C1C6-4940-BF79-61D5438D09C1}" subset="font_id"/><feat class="11." subset="font_size"/>6 </t-style>
          </t>
`

in HTML:
`
 <span class="part">
            <span class="style_italic|superscript">6 </span>
          </span>
`

**Comment by proycon** [comment]
The '|' trick is indeed nothing that FoLiA defines, it's a convention which you're free to adopt, but the tools won't interpret it as anything special (and deep validation would break on it I think). I'm personally more a proponent of simply nesting <t-styles> in such cases, although it is verbose, the folia2html conversion would work as-is then (but even there folia2html is interpreting a 'convention' because FoLiA doesn't predefine sets). It is a matter of how you want to define your vocabulary and FoLiA offers a high degree of freedom in that.

**Comment by pirolen** [comment]
> Ok, I choose par_style and font_style then
> Submitted to Git

Thanks!

One more thing, the extra space issue: it seems to occur around superscripts. 
E.g.
`
<part xml:id="FA-b1_2_kap4_pp297_307_img_1.text.div1.p9.part.2">
          <t class="OCR">
            <t-style><feat class="{53089C5E-F7C2-4D0A-9428-5F35639F1480}" subset="font_id"/><feat class="7.5" subset="font_size"/>De r. r. </t-style>
          </t>
        </part>
        <part xml:id="FA-b1_2_kap4_pp297_307_img_1.text.div1.p9.part.3">
          <t class="OCR">
            <t-style class="superscript"><feat class="{53089C5E-F7C2-4D0A-9428-5F35639F1480}" subset="font_id"/><feat class="7.5" subset="font_size"/>7 </t-style>
          </t>
</part>
`

but there is no space between 'r.' and the superscript '7' in the Abbyy XML:
`
<charParams l="554" t="1337" r="561" b="1349">r</charParams>
<charParams l="563" t="1346" r="566" b="1349">.</charParams></formatting><formatting lang="GermanStandard" ff="Arial" fs="7.5" superscript="1" style="{53089C5E-F7C2-4D0A-9428-5F35639F1480}">
<charParams l="570" t="1329" r="578" b="1340">7</charParams></formatting>
`

**Comment by kosloot** [comment]
I didn't touch the '|' indeed, except for font-size, because sizes are infinite in number. the bold|superscript things ARE countable.
But I could go for the nested \<t-style\> option if you like. I'll put it on the list.
NOTE: maybe we should add the sub/superscript etc. as a feature then (as was originally one of the options considered)

It will make the FoLiA more verbose, of course. in other contexts people are complaining already :) (not about the FoLiA-abby, as no one uses it yet)
Regarding the spaces. I didn't see it as a problem, and would have to look into them. It is not as easy as you might think.

**Comment by pirolen** [comment]
I am fine with how the two of you see it fitting and sustainable.
Much thanks for the extra effort, again!

**Comment by kosloot** [comment]
Ok, now the '|'  trick is gone, and all font properties are added as 'font_property' features,
example fragment:
```xml
          <t class="OCR">
            <t-style>
              <feat class="italic" subset="font_property"/>
              <feat class="superscript" subset="font_property"/>
              <feat class="{969685F8-BA90-4C77-B20B-CCDD69D1DF1E}" subset="font_style"/>
              <feat class="11." subset="font_size"/>3 </t-style>
          </t>
```

Is this workable? Any suggestions for better subset names?

work on spaces is to be done....

**Comment by pirolen** [comment]
Thanks! 
Maybe just that, instead of font_property, "font_typeface" would be a more specific term. (Looked a bit at terminologies.)
In case also the font family (Times, Arial) would be directly propagated as a subset (not just indirectly via font_style), then "font_family" may be fine to use.

**Comment by kosloot** [comment]
So this is done now too: renamed to font_typeface and font_family is added
except from the "spaces" problem, i assume this is finished now?

**Comment by pirolen** [comment]
Yes, thanks! Unless you'd change the t-style as you suggest in https://github.com/proycon/foliatools/issues/26#issuecomment-759565493.
