### ISSUE TITLE
FoLiA-abby: Include paragraph start/end coordinate positions

### ISSUE THREAD

**Issue by pirolen** [LanguageMachines/foliautils#54]
Hopefully one last thing:
if possible, we'd be grateful for an inclusion of paragraph start/end coordinate positions.

Abbyy assigns various infos to each paragraphStyle, such as:
align="Left" startIndent="1100" leftIndent="0" rightIndent="0” 
and it seems that startIndent=“1100” represents a tab-like indent, so far so good.

However, I didn’t see a generic attribute that would reveal if a paragraph ends just because there is no more space on the page, or because it is really the end of that content. 
(E.g. On the attached page, both the body and the footnote sections end in the middle of the sentence, but Abbyy marks them as end-of-paragraph. Which is true for the page, but not for the content.) 
 
It also seems that at the paragraphStyle declarations the paragraph alignment info is just the default ("Left”), and may still get updated at the beginning of a paragraph. It might be also worth propagating the par align=“…” (e.g. “Center”) value from the Abbyy when it is there, and put it as e.g. `feat class=“Center”  subset=“par_align”` for the respective `<p>` in FoLiA.

How do you see it?

![b1_2_mwtext_pp97_352_3](https://user-images.githubusercontent.com/56072981/104501478-13e8ef00-55e0-11eb-8944-bc765e81ae3a.png)

**Comment by kosloot** [comment]
Adding an "align" Feature is easy (already done).

considering coordinates, I don't see exactly what you want now. 
Indeed startIndent and such are found in the pararaphStyle, but no end of paragraph position, so what to do?
Ignore the end? Only add the startposition?

It is also possible to add for each part, the 'l' and 'r' coordinates as found in the <line> nodes. Or even the 't' and 
'b' too?

**Comment by pirolen** [comment]
Thanks very much!

> It is also possible to add for each part, the 'l' and 'r' coordinates as found in the nodes. Or even the 't' and
> 'b' too?

Yes, the idea is simply to propagate all 4 coordinates from the Abbyy `charParams`, both for the start and also for the end character within the given paragraph. 
(The indentation etc. info for paragraphStyle we thankfully have already in the metadata, so there would be no need for duplicating them, it seems.)

The corresponding nodes could be called something like:
par_start_coord, par_end_coord, with each taking the above 4 attribute-value pairs? 
Not yet sure about the formalism.

> Adding an "align" Feature is easy

Great, if you mean the `<text> <par align="Center"...` (Justified, etc.) info, because this value is in fact also important. That's great if you can also propagate it to the FoLiA `<p>`. Maybe as a par_align subset?

**Comment by kosloot** [comment]
Hmm, Whats wrong with only using the info form the \<line\>  nodes? That is much simpler then using the charParmas within.
example:
```xml
<line baseline="1824" l="294" t="1788" r="335" b="1820"><formatting lang="GermanStandard" ff="Arial" fs="6." style="{72CFDA41-3865-4EB2-A00D-0565CA4F2BD7}">
<charParams l="294" t="1790" r="305" b="1819">1</charParams>
<charParams l="315" t="1788" r="335" b="1820">0</charParams></formatting></line></par>
```
I would suggest adding this:
```xml
<p ....>
  <metric class="l" value="294"/>
  <metric class="t" value="1788"/>
  <metric class="r" value="335"/>
  <metric class="b" value="1820"/>
...
</p>
```

imho this is enough information, and much clearer then adding everything twice, with classes like "begin_l" and "end_l" etc.

> Great, if you mean the <text> <par align="Center"... (Justified, etc.) info, because this value is in fact also important. That's great if you can also propagate it to the FoLiA <p>. Maybe as a par_align subset?

that is already implemented :)

**Comment by kosloot** [comment]
Hmm. In hindsight: there are \<par nodes with more then one \<line  node
so the information from the \<line is not enough. But this makes me wonder if it wouldn't be better to add the metric info to every
 \<part\> within the \<p\> nodes? For best granularity?

**Comment by pirolen** [comment]
>  if it wouldn't be better to add the metric info to every <part> within the <p> nodes? For best granularity?

Fine with me.
Just that, still we'd like to have the metric information propagated from both the first and the last line (of the part). 

Having this info, we can always check if there was indentation relative to the margin on both sides, and can compute vertical whitespace as well, for the given text unit on the page. (Such whitespace represents edition logic which we need to make explicit in a subsequent transformation step.)

**Comment by proycon** [comment]
I agree with the metric solution Ko suggested to codify position.

**Comment by kosloot** [comment]
Ok.
I added metrics for both the first and last \<charParam\> from a \<par\> to the folia::Pargraphs like this:
```xml
      <p xml:id="FA-piroska.text.div1.p7">
        <feat class="{70C0E49A-EEFB-45E0-8119-02B965690BD0}" subset="par_style"/>
        <feat class="Justified" subset="par_align"/>
        <metric class="first_char_top" value="1160"/>
        <metric class="first_char_left" value="379"/>
        <metric class="first_char_right" value="409"/>
        <metric class="first_char_bottom" value="1197"/>
        <metric class="last_char_top" value="1174"/>
        <metric class="last_char_left" value="2493"/>
        <metric class="last_char_right" value="2511"/>
        <metric class="last_char_bottom" value="1180"/>
      ...
```

Please comment on the names of the classes.

Also note that in case of a 1 character \<par\> the first* and last* values will be the same

**Comment by pirolen** [comment]
Yes, absolutely fine, thank you very much!
