### ISSUE TITLE
Change FoLiA-correct output extension to ``ticcl.folia.xml`` instead of ``folia.ticcl.xml``

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/foliautils#6]
_From @proycon on March 30, 2017 11:4_

It's conventional for FoLiA documents to end in ``folia.xml`` across various tools

_Copied from original issue: LanguageMachines/ticcltools#3_

**Comment by kosloot** [comment]
@proycon  can we close this issue now?

**Comment by proycon** [comment]
yep
