### ISSUE TITLE
FoLiA-abby: Possible to propagate Abbyy paragraphStyle ID to FoLiA <p> element?

### ISSUE THREAD

**Issue by pirolen** [LanguageMachines/foliautils#63]
Would it be possible to propagate the ID that refers back to the "paragraphStyle" information in the Abbyy XML to the FoLiA, e.g. to include it in the `<p>` element?
The "paragraphStyle" a.o. encodes the function of a paragraph in a document (e.g. main text, footnote, running title, ...), as recognized by the OCR engine or annotated by a human post-corrector; please see below for illustration.

I can imagine that it would be important to keep this info when converting to FoLiA; currently it seems that the ID is not included, while the "paragraphStyle" information is already there as metadata.

<img width="974" alt="image006" src="https://user-images.githubusercontent.com/56072981/128679907-84e8300f-d034-4c26-95d2-f43c2a3f8c6f.png">

**Comment by pirolen** [comment]
Ah, I have just spotted that it is already there, as a feature of the paragraph! Brilliant. Apologies -- closing the issue :)

**Comment by kosloot** [comment]
You are welcome :)

**Comment by pirolen** [comment]
I forgot that we had discussed this earlier already :-o and you implemented the features  👍
