### ISSUE TITLE
FoLiA-page: add support for linebreaks

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/foliautils#65]
PageXML textlines are currently not reflected in the original paragraph text, we can insert linebreaks to make the line more explicit and we can use ``<t-str>`` to more explicitly mark the text lines. These are linked to the ``<str>`` annotations that are produced already (and where in turn an explicit relation with the original PageXML TextLine is stored). The use-case for this that FLAT requires this explicit information to properly display the document, and we may have an annotation task (knaw-huc/golden-agents-htr#1).

I implemented this in the ``page-br`` branch but currently fails because of text validation issue proycon/folia#101.

**Comment by kosloot** [comment]
Assuming this is solved

**Comment by pirolen** [comment]
Would it be possible to treat end-of-line hyphens in the same way as FoLiA-txt does? https://github.com/LanguageMachines/foliautils/issues/67

**Comment by kosloot** [comment]
I assume this is doable. But Page documents have a rather exotic structure, so this needs some studying.

If you could provide me with a SHORT page document with a few hyphens? Maybe soft-hyphens too?

**Comment by kosloot** [comment]
> if you could provide me with a SHORT page document with a few hyphens? Maybe soft-hyphens too?
No need to send it, already found one.

**Comment by pirolen** [comment]
Thank you for looking into it. It is by far not a priority, I was just wondering. Happy that the other tools can do it.

**Comment by kosloot** [comment]
I updated git master now with the newpage branch.
FoLiA-page will now interpret trailing hyphens (both - and  ¬) and add them as ``<t-hbr>`` nodes, just like FoLiA-abby does

@pirolen I tested quite a bit, but feedback is still welcome

**Comment by kosloot** [comment]
seems ok, for now
