### ISSUE TITLE
Cannot pull docker

### ISSUE THREAD

**Issue by VincentCCL** [LanguageMachines/foliautils#69]
[vincent@nero clasabed]$ docker pull proycon/foliautils
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
ERRO[0000] cannot find UID/GID for user vincent: no subuid ranges found for user "vincent" in /etc/subuid - check rootless mode in man pages. 
WARN[0000] Using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids if not using a network user 
WARN[0000] Network file system detected as backing store.  Enforcing overlay option `force_mask="700"`.  Add it to storage.conf to silence this warning 
✔ registry.access.redhat.com/proycon/foliautils:latest
Trying to pull registry.access.redhat.com/proycon/foliautils:latest...
Error: initializing source docker://registry.access.redhat.com/proycon/foliautils:latest: reading manifest latest in registry.access.redhat.com/proycon/foliautils: name unknown: Repo not found

**Comment by proycon** [comment]
We handled this issue over mail already I believe, so closing this here. This had to do with your local podman installation and configuration, nothing with the image as such: Use `podman pull docker.io/proycon/foliautils` if it's not configured to look on docker hub by default.
