### ISSUE TITLE
Change FoLiA extension for FoLiA-langcat

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/foliautils#7]
The current extension for FoLiA-langcat output is *folia.lc.xml

This is not in line with our convention to have *folia.xml as default extension for FoLiA XML documents.

Also: 'lc' for 'langcat' is confusable with 'lower case'.

I recommend changing the FoLiA-langcat extension to: *lang.folia.xml

MRE

**Comment by kosloot** [comment]
Yes this seems a cunning plan.
@proycon this will be implemented soon, an then affect your piccl pipeline

**Comment by kosloot** [comment]
done
