### ISSUE TITLE
FoLiA-txt: paragraph recognition

### ISSUE THREAD

**Issue by pirolen** [LanguageMachines/foliautils#71]
On this .txt file only two paragraphs are generated by FoLiA-txt (or Piereling), although it has several paragraphs, each separated by (several) newlines.

What could be the reason? I'd need to keep all the paragraphs.
Many thanks for checking.

[dipl_parags.txt](https://github.com/LanguageMachines/foliautils/files/12659899/dipl_parags.txt)

**Comment by proycon** [comment]
I think @kosloot can probably say more about FoLiA-txt's behaviour here. 

I do think, even if each newline were naively split into a paragraph, you wouldn't get actual paragraphs, because whatever these numbered blocks represent (page numbers?); they don't seem to be paragraphs. There seem to even be hyphenated words with a newline and one of those number headers in the middle, you wouldn't want a paragraph break there probably.

**Comment by pirolen** [comment]
It's fine to have paragraphs there.
This data originally comes from an HTR engine, and the paragraphs are the actual pagebreaks (I think).

I need to have paragraphs, since this is important in further processing (morphosyntactic analysis).

FoLiA-txt recognizes the first paragraphs, but not any of the further ones. So almost all text is in p.2 which is odd, given all the newlines and newline characters at regular distances :-/ I'd like to understand the reason.

**Comment by pirolen** [comment]
> and one of those number headers in the middle,

Where does that occur? I might have overlooked something, can't see it right now.

**Comment by kosloot** [comment]
Well, I assume this is a bug anyway. FoLiA-txt should indeed generate more than 2 paragraphs.
Despite some oddities like breaking a word on a pagebreak like ``190r``:
```
рьшнемѹ сълажає҆ть сѣмени . вели-

190r
ко гл҃аныи҆мъ съставленїе приносити .
```

**Comment by pirolen** [comment]
Apologies about my troublesome data and workflows!

**Comment by pirolen** [comment]
> Well, I assume this is a bug anyway. FoLiA-txt should indeed generate more than 2 paragraphs. Despite some oddities like breaking a word on a pagebreak like `190r`:

Words ending at any point seem to be quite common in these medieval manuscripts I am processing now. Word segmentation as such did not exist much, so there are often also no word boundaries in the source data (images), only in transcripts the boundaries get inserted.

**Comment by kosloot** [comment]
Wel, the explanation is, that the text is full of ZERO WIDTH NON JOINER symbols.
Unicode U200C or UTF8 E2808C
This confuses all further processing
see: https://unicode-explorer.com/c/200C

It may take some time to think of the best way to handle this. Maybe the crude way is best: removing them

**Comment by pirolen** [comment]
I have seen those characters --- now removed... but the issue seems to remain. 
If I observe the unicode character on the newline, it is  `<CARRIAGE RETURN><LINE FEED>`.

**Comment by kosloot** [comment]
Well. I added code in FoLiA-txt to remove the ZWNJ characters, and now it works as expected.
It detects 32 paragraphs in your example file.

Code committed to Git and now testing

**Comment by kosloot** [comment]
assume this is alright now
