### ISSUE TITLE
Gracefully skipping erroneous files

### ISSUE THREAD

**Issue by pirolen** [LanguageMachines/foliautils#72]
Hi, I was running `FoLiA-txt  --remove-end-hyphens yes -O . *.txt` on a large number of (small) files. After about 100 files got processed, I got this error:

`terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >' Aborted (core dumped)`

Since it left the majority of the files unprocessed, would there be a way that FoLiA-txt skips the erroneous files (and maybe tells which one it was)?

**Comment by pirolen** [comment]
It seems now that the problem was caused by the (proprietary) file name. A lot of the files have a `!` character in the name :-//

**Comment by pirolen** [comment]
So in this sense, no action is required...

**Comment by kosloot** [comment]
Thanx for solving it by yourself :)
Nevertheless I looked into it, and the message you will get in the future is more insightful:

> terminate called after throwing an instance of 'std::runtime_error'
>   what():  unable to generate a Document ID from the filename: 'hypex!'
> Aborted

still not optimal, but ok.

**Comment by pirolen** [comment]
Thank you very much!

**Comment by kosloot** [comment]
FoLiA-txt will now continue with the next file (in git version)
